<script setup lang="ts">
import { ref } from 'vue'

interface Props {
  sql: string
}

defineProps<Props>()

const isExpanded = ref(false)
const copied = ref(false)

const copyToClipboard = async (text: string) => {
  try {
    await navigator.clipboard.writeText(text)
    copied.value = true
    setTimeout(() => copied.value = false, 2000)
  } catch (err) {
    console.error('Failed to copy:', err)
  }
}
</script>

<template>
  <div class="card">
    <div class="flex items-center justify-between mb-4">
      <h3 class="text-lg font-semibold text-slate-800">Generated SQL</h3>
      <button
        @click="isExpanded = !isExpanded"
        class="text-primary-500 hover:text-primary-600 transition-colors"
      >
        <svg 
          class="w-5 h-5 transform transition-transform"
          :class="{ 'rotate-180': isExpanded }"
          fill="none" 
          stroke="currentColor" 
          viewBox="0 0 24 24"
        >
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/>
        </svg>
      </button>
    </div>

    <Transition name="slide">
      <div v-if="isExpanded" class="space-y-4">
        <div class="relative">
          <pre class="bg-slate-900 text-slate-100 p-4 rounded-lg overflow-x-auto text-sm"><code>{{ sql }}</code></pre>
          <button
            @click="copyToClipboard(sql)"
            class="absolute top-2 right-2 p-2 bg-slate-700 hover:bg-slate-600 rounded transition-colors"
          >
            <svg v-if="!copied" class="w-4 h-4 text-slate-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"/>
            </svg>
            <svg v-else class="w-4 h-4 text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/>
            </svg>
          </button>
        </div>

        <div class="p-3 bg-blue-50 border border-blue-200 rounded-lg">
          <p class="text-sm text-blue-800">
            <strong>Note:</strong> This SQL was generated by AI. Always review queries before running them in production.
          </p>
        </div>
      </div>
    </Transition>

    <div v-if="!isExpanded" class="text-sm text-slate-600">
      Click to expand and view the generated SQL query
    </div>
  </div>
</template>